### ISSUE TITLE
Configurable exit flterm sequence

### ISSUE THREAD

**Issue by ewenmcneill** [timvideos/flterm#9]
As of https://github.com/timvideos/flterm/pull/7 (Ctrl-C) and https://github.com/timvideos/flterm/pull/8 (Ctrl-D) it is possible to exit flterm cleanly (0 exit code), which is useful when using, eg, `make firmware-connect` in https://github.com/timvideos/litex-buildenv/.

However both of these sequences are commonly used in, eg, the Linux console, so a `flterm` session connected to a system with a Linux console will now be unable to send either of these sequences.

We should probably (a) make the exit sequence configurable, and (b) consider making the default sequence a less common character sequences.  `Ctrl-]` is conventional for terminal programs, `telnet`, etc for this reason.

**Comment by mithro** [comment]
Going with the telnet one by default seems like a good idea?

**Comment by ewenmcneill** [comment]
From some experimentation, and the [`telnet` manpage](https://linux.die.net/man/1/telnet) the traditional telnet command line option seems to be `-e ESCAPECHAR`, and it seems to accept both a single character, and the `^L` (where `L` is any reasonable character) for `Ctrl-L`.  And both seem to work.

So perhaps we adopt the same command line syntax?

(The `virsh` console connection also uses `Ctrl-]`, at least by default, so it's bound into my finger tips; `telnet` brings up a menu prompt, but `virsh` console just disconnects.  I suspect we want the "just disconnect" behaviour here.)

We might also want another flag to determine whether Ctrl-C, etc, should be interpreted as a local signal, or the `tty` be put in a raw mode where those are not interpreted as local signals.

Ewen

```
debian$ telnet mcneill.gen.nz 80
Trying 203.171.38.149...
Connected to mcneill.gen.nz.
Escape character is '^]'.
^] 

telnet> quit
Connection closed.
```

```
debian$ telnet -e } mcneill.gen.nz 80
Telnet escape character is '}'.
Trying 203.171.38.149...
Connected to mcneill.gen.nz.
Escape character is '}'.
}

telnet> quit
Connection closed.
```
```
debian$ telnet -e ^d mcneill.gen.nz 80
Telnet escape character is '^D'.
Trying 203.171.38.149...
Connected to mcneill.gen.nz.
Escape character is '^D'.

telnet> quit
Connection closed.
```

**Comment by mithro** [comment]
Sounds great to me! Any chance you could implement it?

**Comment by ewenmcneill** [comment]
@mithro I figured you'd say that :-)  Yes, I should be able to implement it, and I've added it to my todo list.  Hopefully sometime in March....

Ewen

**Comment by ewenmcneill** [comment]
Closing issue, after 5 years, since I never did get around to implementing this change to the `flterm` exit sequence.  And upstream `litex` has moved on a lot since then (and has its own terminal access program).  So I don't think there's any point in implementing this in `litex-buildenv` any longer.

Ewen
